export const HASUPDATE_ACCOUNT = 'HASUPDATE_ACCOUNT';
export const LOAD_ACCOUNT = 'LOAD_ACCOUNT';
export const ACCOUNT_GETBYID = 'ACCOUNT_GETBYID';
export const ACCOUNT_OPEN_VIEWDETAIL = 'ACCOUNT_VIEWDETAIL';
export const ACCOUNT_CLOSE_VIEWDETAIL = 'ACCOUNT_CLOSE_VIEWDETAIL';

export const ACCOUNT_EDIT_OPEN = 'ACCOUNT_EDIT_OPEN';
export const ACCOUNT_EDIT_CLOSE = 'ACCOUNT_EDIT_CLOSE';
export const ACCOUNT_EDIT_SAVE = 'ACCOUNT_EDIT_SAVE';
export const ACCOUNT_SEARCH_SAVE = 'ACCOUNT_SEARCH_SAVE';

export const ACCOUNT_RSPW_OPEN = 'ACCOUNT_RSPW_OPEN';
export const ACCOUNT_RSPW_CLOSE = 'ACCOUNT_RSPW_CLOSE';
export const ACCOUNT_RSPW_SAVE = 'ACCOUNT_RSPW_SAVE';

export const LOAD_ACCOUNT_DETAILS = 'LOAD_ACCOUNT_DETAILS';
export const ACCOUNT_CHANGEPW_OPEN = 'ACCOUNT_CHANGEPW_OPEN';
export const ACCOUNT_CHANGEPW_CLOSE = 'ACCOUNT_CHANGEPW_CLOSE';
export const ACCOUNT_CHANGEPW_SAVE = 'ACCOUNT_CHANGEPW_SAVE';
