export const HASUPDATE_BANNER = 'HASUPDATE_BANNER';
export const LOAD_BANNER = 'LOAD_BANNER';
export const BANNER_GETBYID = 'BANNER_GETBYID';
export const BANNER_OPEN_VIEWDETAIL = 'BANNER_VIEWDETAIL';
export const BANNER_CLOSE_VIEWDETAIL = 'BANNER_CLOSE_VIEWDETAIL';

export const BANNER_EDIT_OPEN = 'BANNER_EDIT_OPEN';
export const BANNER_EDIT_CLOSE = 'BANNER_EDIT_CLOSE';
export const BANNER_EDIT_SAVE = 'BANNER_EDIT_SAVE';
export const BANNER_SEARCH_SAVE = 'BANNER_SEARCH_SAVE';
