export const HASUPDATE_CATEGORYNEWS = 'HASUPDATE_CATEGORYNEWS';
export const LOAD_CATEGORYNEWS = 'LOAD_CATEGORYNEWS';
export const CATEGORYNEWS_GETBYID = 'CATEGORYNEWS_GETBYID';
export const CATEGORYNEWS_OPEN_VIEWDETAIL = 'CATEGORYNEWS_VIEWDETAIL';
export const CATEGORYNEWS_CLOSE_VIEWDETAIL = 'CATEGORYNEWS_CLOSE_VIEWDETAIL';

export const CATEGORYNEWS_EDIT_OPEN = 'CATEGORYNEWS_EDIT_OPEN';
export const CATEGORYNEWS_EDIT_CLOSE = 'CATEGORYNEWS_EDIT_CLOSE';
export const CATEGORYNEWS_EDIT_SAVE = 'CATEGORYNEWS_EDIT_SAVE';
export const CATEGORYNEWS_SEARCH_SAVE = 'CATEGORYNEWS_SEARCH_SAVE';
