export const HASUPDATE_COMMONCONFIG = 'HASUPDATE_COMMONCONFIG';
export const LOAD_COMMONCONFIG = 'LOAD_COMMONCONFIG';
export const COMMONCONFIG_GETBYID = 'COMMONCONFIG_GETBYID';
export const COMMONCONFIG_OPEN_VIEWDETAIL = 'COMMONCONFIG_VIEWDETAIL';
export const COMMONCONFIG_CLOSE_VIEWDETAIL = 'COMMONCONFIG_CLOSE_VIEWDETAIL';

export const COMMONCONFIG_EDIT_OPEN = 'COMMONCONFIG_EDIT_OPEN';
export const COMMONCONFIG_EDIT_CLOSE = 'COMMONCONFIG_EDIT_CLOSE';
export const COMMONCONFIG_EDIT_SAVE = 'COMMONCONFIG_EDIT_SAVE';
export const COMMONCONFIG_SEARCH_SAVE = 'COMMONCONFIG_SEARCH_SAVE';
export const COMMONCONFIG_SEARCH_TOGGLE = 'COMMONCONFIG_SEARCH_TOGGLE';
