export const HASUPDATE_DANGKYHIENTANG = 'HASUPDATE_DANGKYHIENTANG';
export const LOAD_DANGKYHIENTANG = 'LOAD_DANGKYHIENTANG';

export const LOAD_DANGKYHIENTANG_FILE = 'LOAD_DANGKYHIENTANG_FILE';
export const DANGKYHIENTANG_GETBYID = 'DANGKYHIENTANG_GETBYID';
export const DANGKYHIENTANG_OPEN_VIEWDETAIL = 'DANGKYHIENTANG_VIEWDETAIL';
export const DANGKYHIENTANG_CLOSE_VIEWDETAIL =
    'DANGKYHIENTANG_CLOSE_VIEWDETAIL';

export const DANGKYHIENTANG_EDIT_OPEN = 'DANGKYHIENTANG_EDIT_OPEN';
export const DANGKYHIENTANG_EDIT_CLOSE = 'DANGKYHIENTANG_EDIT_CLOSE';
export const DANGKYHIENTANG_EDIT_SAVE = 'DANGKYHIENTANG_EDIT_SAVE';
export const DANGKYHIENTANG_SEARCH_SAVE = 'DANGKYHIENTANG_SEARCH_SAVE';

export const DANGKYHIENTANG_CHANGESTATUS_OPEN =
    'DANGKYHIENTANG_CHANGESTATUS_OPEN';
export const DANGKYHIENTANG_CHANGESTATUS_CLOSE =
    'DANGKYHIENTANG_CHANGESTATUS_CLOSE';
export const DANGKYHIENTANG_CHANGESTATUS_SAVE =
    'DANGKYHIENTANG_CHANGESTATUS_SAVE';
