export const HASUPDATE_DANGKYCHOGHEPTANG = 'HASUPDATE_DANGKYCHOGHEPTANG';
export const LOAD_DANGKYCHOGHEPTANG = 'LOAD_DANGKYCHOGHEPTANG';
export const LOAD_DANGKYCHOGHEPTANG_THAN_PDF =
    'LOAD_DANGKYCHOGHEPTANG_THAN_PDF';
export const LOAD_DANGKYCHOGHEPTANG_KHAC_PDF =
    'LOAD_DANGKYCHOGHEPTANG_KHAC_PDF';
export const DANGKYCHOGHEPTANG_GETBYID = 'DANGKYCHOGHEPTANG_GETBYID';
export const DANGKYCHOGHEPTANG_OPEN_VIEWDETAIL = 'DANGKYCHOGHEPTANG_VIEWDETAIL';
export const DANGKYCHOGHEPTANG_CLOSE_VIEWDETAIL =
    'DANGKYCHOGHEPTANG_CLOSE_VIEWDETAIL';

export const DANGKYCHOGHEPTANG_OPEN_CREATE = 'DANGKYCHOGHEPTANG_OPEN_CREATE';
export const DANGKYCHOGHEPTANG_CLOSE_CREATE = 'DANGKYCHOGHEPTANG_CLOSE_CREATE';

export const DANGKYCHOGHEPTANG_EDIT_OPEN = 'DANGKYCHOGHEPTANG_EDIT_OPEN';
export const DANGKYCHOGHEPTANG_EDIT_CLOSE = 'DANGKYCHOGHEPTANG_EDIT_CLOSE';
export const DANGKYCHOGHEPTANG_EDIT_SAVE = 'DANGKYCHOGHEPTANG_EDIT_SAVE';
export const DANGKYCHOGHEPTANG_SEARCH_SAVE = 'DANGKYCHOGHEPTANG_SEARCH_SAVE';

export const DANGKYCHOGHEPTANG_CHANGESTATUS_OPEN =
    'DANGKYCHOGHEPTANG_CHANGESTATUS_OPEN';
export const DANGKYCHOGHEPTANG_CHANGESTATUS_CLOSE =
    'DANGKYCHOGHEPTANG_CHANGESTATUS_CLOSE';
export const DANGKYCHOGHEPTANG_CHANGESTATUS_SAVE =
    'DANGKYCHOGHEPTANG_CHANGESTATUS_SAVE';

export const DANGKYCHOGHEPTANG_THONGBAOXN_OPEN =
    'DANGKYCHOGHEPTANG_THONGBAOXN_OPEN';
export const DANGKYCHOGHEPTANG_THONGBAOXNMUTI_OPEN =
    'DANGKYCHOGHEPTANG_THONGBAOXNMUTI_OPEN';
export const DANGKYCHOGHEPTANG_THONGBAOXNMUTI_CLOSE =
    'DANGKYCHOGHEPTANG_THONGBAOXNMUTI_CLOSE';
export const DANGKYCHOGHEPTANG_THONGBAOXNMUTI_SAVE =
    'DANGKYCHOGHEPTANG_THONGBAOXNMUTI_SAVE';

export const DANGKYCHOGHEPTANG_THONGBAOXN_CLOSE =
    'DANGKYCHOGHEPTANG_THONGBAOXN_CLOSE';
export const DANGKYCHOGHEPTANG_THONGBAOXN_SAVE =
    'DANGKYCHOGHEPTANG_THONGBAOXN_SAVE';
export const DANGKYCHOGHEPTANG_CHANGETYPECREATE =
    'DANGKYCHOGHEPTANG_CHANGETYPECREATE';
export const DANGKYCHOGHEPTANG_SEARCHTOGGLE = 'DANGKYCHOGHEPTANG_SEARCHTOGGLE';
export const KQXETNGHIEM_EDIT_OPEN = 'KQXETNGHIEM_EDIT_OPEN';
export const KQXETNGHIEM_EDIT_CLOSE = 'KQXETNGHIEM_EDIT_CLOSE';
export const KQXETNGHIEM_EDIT_SAVE = 'KQXETNGHIEM_EDIT_SAVE';
export const KQXETNGHIEM_OPEN_VIEWDETAIL = 'KQXETNGHIEM_VIEWDETAIL';
export const KQXETNGHIEM_CLOSE_VIEWDETAIL = 'KQXETNGHIEM_CLOSE_VIEWDETAIL';
export const HASUPDATE_KQXETNGHIEM = 'HASUPDATE_KQXETNGHIEM';
export const KQXETNGHIEM_CLOSE_CREATE = 'KQXETNGHIEM_CLOSE_CREATE';
