export const HASUPDATE_DMDULIEUDANHMUC = 'HASUPDATE_DMDULIEUDANHMUC';
export const LOAD_DMDULIEUDANHMUC = 'LOAD_DMDULIEUDANHMUC';
export const DMDULIEUDANHMUC_GETBYID = 'DMDULIEUDANHMUC_GETBYID';
export const DMDULIEUDANHMUC_OPEN_VIEWDETAIL = 'DMDULIEUDANHMUC_VIEWDETAIL';
export const DMDULIEUDANHMUC_CLOSE_VIEWDETAIL =
    'DMDULIEUDANHMUC_CLOSE_VIEWDETAIL';

export const DMDULIEUDANHMUC_EDIT_OPEN = 'DMDULIEUDANHMUC_EDIT_OPEN';
export const DMDULIEUDANHMUC_EDIT_CLOSE = 'DMDULIEUDANHMUC_EDIT_CLOSE';
export const DMDULIEUDANHMUC_EDIT_SAVE = 'DMDULIEUDANHMUC_EDIT_SAVE';
export const DMDULIEUDANHMUC_SEARCH_SAVE = 'DMDULIEUDANHMUC_SEARCH_SAVE';
