export const HASUPDATE_DMNHOM = 'HASUPDATE_DMNHOM';
export const LOAD_DMNHOM = 'LOAD_DMNHOM';
export const DMNHOM_GETBYID = 'DMNHOM_GETBYID';
export const DMNHOM_OPEN_VIEWDETAIL = 'DMNHOM_VIEWDETAIL';
export const DMNHOM_CLOSE_VIEWDETAIL = 'DMNHOM_CLOSE_VIEWDETAIL';

export const DMNHOM_EDIT_OPEN = 'DMNHOM_EDIT_OPEN';
export const DMNHOM_EDIT_CLOSE = 'DMNHOM_EDIT_CLOSE';
export const DMNHOM_EDIT_SAVE = 'DMNHOM_EDIT_SAVE';
export const DMNHOM_SEARCH_SAVE = 'DMNHOM_SEARCH_SAVE';
