export const HASUPDATE_HOIDAP = 'HASUPDATE_HOIDAP';
export const LOAD_HOIDAP = 'LOAD_HOIDAP';
export const HOIDAP_GETBYID = 'HOIDAP_GETBYID';
export const HOIDAP_OPEN_VIEWDETAIL = 'HOIDAP_VIEWDETAIL';
export const HOIDAP_CLOSE_VIEWDETAIL = 'HOIDAP_CLOSE_VIEWDETAIL';

export const HOIDAP_EDIT_OPEN = 'HOIDAP_EDIT_OPEN';
export const HOIDAP_EDIT_CLOSE = 'HOIDAP_EDIT_CLOSE';
export const HOIDAP_EDIT_SAVE = 'HOIDAP_EDIT_SAVE';
export const HOIDAP_SEARCH_SAVE = 'HOIDAP_SEARCH_SAVE';
