export const HASUPDATE_HUYEN = 'HASUPDATE_HUYEN';
export const LOAD_HUYEN = 'LOAD_HUYEN';
export const LOAD_HUYEN_PARRENT = 'LOAD_HUYEN_PARRENT';
export const HUYEN_GETBYID = 'HUYEN_GETBYID';
export const HUYEN_OPEN_VIEWDETAIL = 'HUYEN_VIEWDETAIL';
export const HUYEN_CLOSE_VIEWDETAIL = 'HUYEN_CLOSE_VIEWDETAIL';

export const HUYEN_EDIT_OPEN = 'HUYEN_EDIT_OPEN';
export const HUYEN_EDIT_CLOSE = 'HUYEN_EDIT_CLOSE';
export const HUYEN_EDIT_SAVE = 'HUYEN_EDIT_SAVE';
export const HUYEN_SEARCH_SAVE = 'HUYEN_SEARCH_SAVE';
