export const HASUPDATE_KQXETNGHIEM = 'HASUPDATE_KQXETNGHIEM';
export const LOAD_KQXETNGHIEM = 'LOAD_KQXETNGHIEM';
export const LOAD_KQXETNGHIEM_THAN_PDF = 'LOAD_KQXETNGHIEM_THAN_PDF';
export const LOAD_KQXETNGHIEM_KHAC_PDF = 'LOAD_KQXETNGHIEM_KHAC_PDF';
export const KQXETNGHIEM_GETBYID = 'KQXETNGHIEM_GETBYID';
export const KQXETNGHIEM_OPEN_VIEWDETAIL = 'KQXETNGHIEM_VIEWDETAIL';
export const KQXETNGHIEM_CLOSE_VIEWDETAIL = 'KQXETNGHIEM_CLOSE_VIEWDETAIL';

export const KQXETNGHIEM_OPEN_CREATE = 'KQXETNGHIEM_OPEN_CREATE';
export const KQXETNGHIEM_CLOSE_CREATE = 'KQXETNGHIEM_CLOSE_CREATE';

export const KQXETNGHIEM_EDIT_OPEN = 'KQXETNGHIEM_EDIT_OPEN';
export const KQXETNGHIEM_EDIT_CLOSE = 'KQXETNGHIEM_EDIT_CLOSE';
export const KQXETNGHIEM_EDIT_SAVE = 'KQXETNGHIEM_EDIT_SAVE';
export const KQXETNGHIEM_SEARCH_SAVE = 'KQXETNGHIEM_SEARCH_SAVE';

export const KQXETNGHIEM_CHANGESTATUS_OPEN = 'KQXETNGHIEM_CHANGESTATUS_OPEN';
export const KQXETNGHIEM_CHANGESTATUS_CLOSE = 'KQXETNGHIEM_CHANGESTATUS_CLOSE';
export const KQXETNGHIEM_CHANGESTATUS_SAVE = 'KQXETNGHIEM_CHANGESTATUS_SAVE';

export const KQXETNGHIEM_THONGBAOXN_OPEN = 'KQXETNGHIEM_THONGBAOXN_OPEN';
export const KQXETNGHIEM_THONGBAOXN_CLOSE = 'KQXETNGHIEM_THONGBAOXN_CLOSE';
export const KQXETNGHIEM_THONGBAOXN_SAVE = 'KQXETNGHIEM_THONGBAOXN_SAVE';
export const KQXETNGHIEM_CHANGETYPECREATE = 'KQXETNGHIEM_CHANGETYPECREATE';
export const KQXETNGHIEM_SEARCHTOGGLE = 'KQXETNGHIEM_SEARCHTOGGLE';
