export const HASUPDATE_MODULE = 'HASUPDATE_MODULE';
export const LOAD_MODULE = 'LOAD_MODULE';
export const MODULE_GETBYID = 'MODULE_GETBYID';
export const MODULE_OPEN_VIEWDETAIL = 'MODULE_VIEWDETAIL';
export const MODULE_CLOSE_VIEWDETAIL = 'MODULE_CLOSE_VIEWDETAIL';

export const MODULE_EDIT_OPEN = 'MODULE_EDIT_OPEN';
export const MODULE_EDIT_CLOSE = 'MODULE_EDIT_CLOSE';
export const MODULE_EDIT_SAVE = 'MODULE_EDIT_SAVE';
export const MODULE_SEARCH_SAVE = 'MODULE_SEARCH_SAVE';
