export const HASUPDATE_OPERATION = 'HASUPDATE_OPERATION';
export const LOAD_OPERATION = 'LOAD_OPERATION';
export const OPERATION_GETBYID = 'OPERATION_GETBYID';
export const OPERATION_OPEN_VIEWDETAIL = 'OPERATION_VIEWDETAIL';
export const OPERATION_CLOSE_VIEWDETAIL = 'OPERATION_CLOSE_VIEWDETAIL';

export const OPERATION_EDIT_OPEN = 'OPERATION_EDIT_OPEN';
export const OPERATION_EDIT_CLOSE = 'OPERATION_EDIT_CLOSE';
export const OPERATION_EDIT_SAVE = 'OPERATION_EDIT_SAVE';
export const OPERATION_SEARCH_SAVE = 'OPERATION_SEARCH_SAVE';
