export const HASUPDATE_ROLE = 'HASUPDATE_ROLE';
export const LOAD_ROLE = 'LOAD_ROLE';
export const ROLE_GETBYID = 'ROLE_GETBYID';
export const ROLE_OPEN_VIEWDETAIL = 'ROLE_VIEWDETAIL';
export const ROLE_CLOSE_VIEWDETAIL = 'ROLE_CLOSE_VIEWDETAIL';

export const ROLE_EDIT_OPEN = 'ROLE_EDIT_OPEN';
export const ROLE_EDIT_CLOSE = 'ROLE_EDIT_CLOSE';
export const ROLE_EDIT_SAVE = 'ROLE_EDIT_SAVE';
export const ROLE_SEARCH_SAVE = 'ROLE_SEARCH_SAVE';
