export const HASUPDATE_TINH = 'HASUPDATE_TINH';
export const LOAD_TINH = 'LOAD_TINH';
export const TINH_GETBYID = 'TINH_GETBYID';
export const TINH_OPEN_VIEWDETAIL = 'TINH_VIEWDETAIL';
export const TINH_CLOSE_VIEWDETAIL = 'TINH_CLOSE_VIEWDETAIL';

export const TINH_EDIT_OPEN = 'TINH_EDIT_OPEN';
export const TINH_EDIT_CLOSE = 'TINH_EDIT_CLOSE';
export const TINH_EDIT_SAVE = 'TINH_EDIT_SAVE';
export const TINH_SEARCH_SAVE = 'TINH_SEARCH_SAVE';
