export const HASUPDATE_TINTUC = 'HASUPDATE_TINTUC';
export const LOAD_TINTUC = 'LOAD_TINTUC';
export const TINTUC_GETBYID = 'TINTUC_GETBYID';
export const TINTUC_OPEN_VIEWDETAIL = 'TINTUC_VIEWDETAIL';
export const TINTUC_CLOSE_VIEWDETAIL = 'TINTUC_CLOSE_VIEWDETAIL';

export const TINTUC_EDIT_OPEN = 'TINTUC_EDIT_OPEN';
export const TINTUC_EDIT_CLOSE = 'TINTUC_EDIT_CLOSE';
export const TINTUC_EDIT_SAVE = 'TINTUC_EDIT_SAVE';
export const TINTUC_SEARCH_SAVE = 'TINTUC_SEARCH_SAVE';
// Lấy tin danh mục category
export const TINTUC_GET_CATEGORY = 'TINTUC_GET_CATEGORY';
