export const HASUPDATE_TOPHUTRACH = 'HASUPDATE_TOPHUTRACH';
export const LOAD_TOPHUTRACH = 'LOAD_TOPHUTRACH';
export const TOPHUTRACH_GETBYID = 'TOPHUTRACH_GETBYID';
export const TOPHUTRACH_OPEN_VIEWDETAIL = 'TOPHUTRACH_VIEWDETAIL';
export const TOPHUTRACH_CLOSE_VIEWDETAIL = 'TOPHUTRACH_CLOSE_VIEWDETAIL';

export const TOPHUTRACH_EDIT_OPEN = 'TOPHUTRACH_EDIT_OPEN';
export const TOPHUTRACH_EDIT_CLOSE = 'TOPHUTRACH_EDIT_CLOSE';
export const TOPHUTRACH_EDIT_SAVE = 'TOPHUTRACH_EDIT_SAVE';
export const TOPHUTRACH_SEARCH_SAVE = 'TOPHUTRACH_SEARCH_SAVE';
